---

 - hosts: web
   become: yes

   tasks:

    - name: Install script
      template:
        src: /etc/ansible/common/files/testweb.sh
        dest: /home/mentor/testweb.sh
        mode: 0777
    - name: Line test
      lineinfile:
       path: /home/mentor/testweb.sh
       insertafter: EOF
       line: "{{ item }}"
       state: present
      with_items:
      - 'date &>> /var/log/web.log'
      - 'nginx -t &>>/var/log/web.log'
